---
title: "Data and Measurement"
output:
  html_document:
    theme: 
       bootswatch: minty
    df_print: kable
    code_folding: hide 
---

```{r, echo = F}
library(formatR)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=20),tidy=TRUE)
```


# Tutorial 5

In this tutorial, we will utilize the "SAQ.sav" dataset. This dataset comprises 23 variables measured on a 5-point Likert scale and includes data from 2,571 participants. The items included are:

1. Statistics makes me cry.
2. My friends will think I’m stupid for not being able to cope with SPSS.
3. Standard deviations excite me.
4. I dream that Pearson is attacking me with correlation coefficients.
5. I don’t understand statistics.
6. I have little experience of computers.
7. All computers hate me.
8. I have never been good at mathematics.
9. My friends are better at statistics than me.
10. Computers are useful only for playing games.
11. I did badly at mathematics at school.
12. People try to tell you that SPSS makes statistics easier to understand but it doesn’t.
13. I worry that I will cause irreparable damage because of my incompetenece with computers.
14. Computers have minds of their own and deliberately go wrong whenever I use them.
15. Computers are out to get me.
16. I weep openly at the mention of central tendency.
17. I slip into a coma whenever I see an equation.
18. SPSS always crashes when I try to use it.
19. Everybody looks at me when I use SPSS.
20. I can’t sleep for thoughts of eigen vectors.
21. I wake up under my duvet thinking that I am trapped under a normal distribution.
22. My friends are better at SPSS than I am.
23. If I’m good at statistics my friends will think I’m a nerd.


##  {.tabset .tabset-fade .tabset-pills}
### Exercise  

1. Load the data to the environment. If you use read.spss function set the use.value.labels argument to FALSE to avoid converting numerical variables (with value labels) to factors as the functions we will use (alpha() and fa()) require numerical variables.

2. Explore the data set. Suggestion: Try the describe() function from the psych.

3. Calculate the correlation matrix (Remember Tutorial 3 - Exercise 2?) and round the correlations to two decimal places.

4. We can also plot correlation matrices using the cor.plot() function from the psych package. Try this out - I suggest you set the "upper" argument to FALSE to get a better plot - and see if it matches your results from the previous exercise.

5. Even if you enlarge the diagram, discerning the variable names on the x-axis remains challenging because we have many variables and long variable names. Therefore, change the variable names in your data frame from "Question_1", "Question_2" etc. to "q1", "q2" etc. You can accomplish this using the names() or colnames() functions together with the gsub() function. Then display the correlation matrix again and see if you can find clusters of variables that exhibit stronger correlations among themselves compared to other groups of variables.

6. According to Field (2019), items 2, 9, 19, 22 and 23 are measuring a specific type of fear, namely, fear of peer evaluation. Create a new dataframe consisting only of these five items. 

7. Find the cronbach's alpha using the alpha() function from psych package. Note: ggplot2 also has a function called alpha and if you’ve loaded ggplot2, the alpha function in ggplot2 may be called instead. to avoid this call the function using psych::alpha().

8. Interpret the results.
