---
title: "Data and Measurement"
output:
  html_document:
    theme: 
       bootswatch: minty
    df_print: kable
    code_folding: hide 
---

# Tutorial 1
In this exercise tutorial, we will explore several data wrangling and descriptive statistics tasks using the dataset named educ_inc_age_data.csv. This dataset contains information about individuals' age, income, and education level.

## Some basics

- In R, the code is entered into the script and the results are displayed in the console.

- In R, we often preserve specific values as 'objects' by using the assignment symbol (<-). Objects can include individual values, vectors, strings, entire data sets, functions, statistical models and more. This allows us to refer to them again in the future. It is important that the object names are clear and logical.

- R has many integrated functions for many different purposes. They all have the same basic format: function_name(argument1 = value 1, argument2 = value 2, …)

- You can display the arguments for a function by typing ‘?function_name’ in the console. Not all arguments require values – for some, R has a default value that it will use if you don’t specify it.

- R is sensitive to parentheses (every open parenthesis should have a corresponding closed parenthesis), capitalization (R differentiates between upper and lower case letters), spelling and quotation marks (characters/strings should be in quotation marks (e.g., "pear")).

- R is insensitive to spaces and line breaks. Including spaces makes your code more readable. While line breaks are not essential, they can help make your code fit better on the screen.

- It's important to note that everything in your environment and history will be (or should be) cleared at the conclusion of each session.Ensure that your script encompasses all the necessary code required to execute your analysis.

- Packages are Need to be installed once (install.packages(“package_name”)), and loaded every time you open R (library(package_name)).

##  {.tabset .tabset-fade .tabset-pills}
### Exercise 1 - Intro to R  
1. Create a numeric vector with numbers from 1 to 100 called id.

2. Create a numeric vector containing the following numbers: 3, 5, 8, 9, 67

3. Check whether the vector you have created is actually numeric.

4. Create a character vector with apple, banana, orange, pear and persimmon. 

5. Check whether the vector you have created is a character vector

6. Create a matrix with 5 rows and 2 columns. The first column contains the following numbers: 3, 5, 8, 9, 67 and the second column contains the following strings: "apple", "banana", "orange", "pear", "persimmon".

7. Create the same matrix as in step 6 by combining the two vectors you created in step 2 and 3.

8. Would it be possible to create a data frame by combining the three vectors you created in steps 1, 2 and 3? Try it out and see what happens. Note that the vector you created in step 1 has  a different length than the vectors in steps 2 and 3.

9. Create a data frame consisting of 50 rows and three variables: `name`, `age`, and `city`.
- The `name` variable should include names randomly selected from the list: "John", "Alice", "Emma", "Janneke", and "Jelle".
- The `age` variable should contain random draws from a normal distribution with a mean of 0 and a standard deviation of 5.
- The `city` variable should be randomly selected from the cities: "New York", "Los Angeles", and "Chicago". The probability of being chosen should be 0.3 for "New York" 0.6 for "Chicago", and 0.1 for "Los Angeles". 
After creating the data frame, check the frequency table of the variable `city`.

10. Execute your code from step 9 again and check the frequencies of the variable `city` or the values of the variables `name` and `age` once more. Do you see any differences?

11. To ensure reproducibility, set the seed and then run your code again.

### Exercise 2 - Data wrangling
1. Load the dataset and display its structure, along with its first and last five observations.

2. Create a new dataset by filtering to include only individuals with an `income` greater than $50,000.

3. How many observations does this new dataset have? 

4. Sort the dataset based on `age` in ascending order.

5. Group the data by `education level` and calculate the mean `income` for each group.

6. Create a new variable named "age_group" categorizing individuals into three age groups: "Young" (`age` < 30), "Middle-aged" (30 <= `age` < 65), and "Elderly" (`age` >= 65).

7. Add a new variable called age_squared which is the square of the `age` variable

8. Remove the variable `age_squared` from the dataset.

9. What is the value of `education` for row 14 and value of `age` for row 3?

10. Identify the row numbers of observations where `age` is 25 or less. Then, using these row numbers, extract the corresponding `income` values. 

11. Convert the variable `age` to character.

12. Convert the variable `age` to numeric

13. Check for missing values in the dataset.

### Exercise 3 - Descriptive statistics

1. Compute the mean, median, and mode for the `age` variable.

2. Compute the range for `income` variable.

3. Compute the variance and standard deviation for the `age` variable.

4. Compute the 25th, 50th (median), and 75th percentiles, as well as the interquartile range for the `income` variable.

5. Compute the Z-scores for the `age` variable.

6. Compute the Z-score for `income` = 14853

7. Ask for summary statistics for each variable in the dataset using one function. 


